### ISSUE TITLE
Automatic indentation stopped working shortly after installation.

### ISSUE THREAD

**Issue by weiss-d** [ChristianChiarulli/LunarVim#181]
I've installed this config by instructions in 'Install In One Command!' section.
Then I executed `:LspInstall efm` and `:LspInstall python`.
At first everything was running smoothly. But after several `:w` commands I noticed that automatic indentation doesn't work any more. I.e. when pressing `Enter` after defining a function next line should start with 4 spaces, but now it starts at the same level as previous line. Same for JS.

![image](https://user-images.githubusercontent.com/62437174/112760824-fd5c0c80-9000-11eb-9100-a3dabe9316de.png)

And there is this weird message at the bottom.
![image](https://user-images.githubusercontent.com/62437174/112760450-aace2080-8fff-11eb-90a4-ee63d5abba98.png)

I'm running Arch-based Linux with `neovim-nightly-git` package installed:
```
❯ nvim --version                                                                                                                                                       INSERT
NVIM v0.5.0-dev+1177-g095f5da79
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/sbin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/main-builder/pkgwork/src/build/config -I/home/main-builder/pkgwork/src/neovim-nightly-git/src -I/usr/include -I/home/main-builder/pkgwork/src/build/src/nvim/auto -I/home/main-builder/pkgwork/src/build/include
Compiled by main-builder

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by ChristianChiarulli** [comment]
hmm, that's my autopairs plugin called `lexima`, let me see if I don't get indentation in python

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/112765745-90cf1680-8fdc-11eb-809c-5b391c84f5c7.png)

It's a problem with treesitters builtin indent

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/112765920-6a5dab00-8fdd-11eb-95a5-c6f1bb637c77.png)

This fixed it

**Comment by ChristianChiarulli** [comment]
There will still be that annoying lexima output tho, until I either fix it, or a better autopair plugin comes around that plays nice with compe,  but that's a lower priority.

**Comment by weiss-d** [comment]
It works now, but only for Python. No autoindent for other languages (tried JS, HTML, C and even Lua).

![image](https://user-images.githubusercontent.com/62437174/112792310-e272b200-906b-11eb-89f0-3db31ab76d5d.png)

**Comment by ChristianChiarulli** [comment]
Maybe I should just disable it totally for now, it was helpful with jsx tho.

**Comment by ChristianChiarulli** [comment]
@weiss-d Ok, soI have moved back to autopairs things should be working after an update.

**Comment by weiss-d** [comment]
I have the following error after `git pull` from `~/.config/nvim/`:

![image](https://user-images.githubusercontent.com/62437174/112862826-d82dd380-90be-11eb-9171-b30d8bcf9ff8.png)

Or I should have updated it some other way?

**Comment by weiss-d** [comment]
Well, after `:PackerUpdate` again I saw this, and then after restart everything is working normally.
![image](https://user-images.githubusercontent.com/62437174/112863169-3d81c480-90bf-11eb-8cbf-3081bf21cab2.png)

**Comment by weiss-d** [comment]
Stopped working again after today's update.

**Comment by weiss-d** [comment]
Here's the problem: autoindent work only when I use `o` to make a new line. In other cases it doesn't work:
![python_indent_error](https://user-images.githubusercontent.com/62437174/113247767-4ee7ee00-92c4-11eb-94b1-eb3c0d33891d.gif)

Just pulled the latest changes and executed `:PackerUpdate`. Still the same.

**Comment by rebuilt** [comment]
The following did not work for me. 
```bash
indent = {enable = true, disable = {"python"}},
```

However, turning off indenting in the python config did work for me.  Add this line.

```bash
indent = {enable = false},
```

To lua/lv-globals.lua, line 23
```bash
    python = {
        linter = '',
        -- @usage can be 'yapf', 'black'
        formatter = '',
        autoformat = false,
        indent = {enable = false},
        isort = false,
        diagnostics = {virtual_text = true, signs = true, underline = true}
    },
```

Is it possible indenting is set to 'on' by default if not specified, thereby overriding the treesitter configs?

**Comment by vpeopleonatank** [comment]
I 've faced same issue when use LunarVim config ( `indent` = false in tree-sitter ). When I use my old lua-based neovim config with tree-sitter installed, python indent work normally.

**Comment by weiss-d** [comment]
Today I've once more cleared `.config/nvim` and other related folders and installed LunarVim from the `rolling` branch. Python automatic indentation still doesn't work. Then I've installed LVIM for kicks and indentation works perfectly fine there.
So maybe, I thought, it makes sense to have a sneaky peek at its code?)

**Comment by weiss-d** [comment]
> I 've faced same issue when use LunarVim config ( `indent` = false in tree-sitter ). When I use my old lua-based neovim config with tree-sitter installed, python indent work normally.

as for this, I ripgrepped indent setting in my home directory like this: `rg -. "indent ?= ?([Ff]alse|[Tt]rue)"`

and that's what I got concerning nvim:
```
.config/nvim/lua/settings.lua
37:opt.smartindent = true -- make indenting smarter again
.config/nvim/lua/plugins.lua
195:      vim.g.indent_blankline_show_trailing_blankline_indent = false
```

**Comment by abzcoding** [comment]
@weiss-d can you test if this fixes your issue or not :
add the following line to `lv-config.lua` 
> make sure you're on `rolling` branch
```lua
O.treesitter.indent.enable = false
```

**Comment by weiss-d** [comment]
Yep, that works. Thanks a lot!

**Comment by ChristianChiarulli** [comment]
@abzcoding should this be a default?

**Comment by abzcoding** [comment]
> @abzcoding should this be a default?

probably yeah, the treesitter indent is a bit unstable
